/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Room_class.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import {  selectPath } from '../../../Common/Utils/Utils'
import { REDUCE_SCALE_DOOR, SCENE_LIGHT_INTENSITY} from '../Modifiers'

export function Class(props: any) {
  const group = useRef()
  const { nodes, materials } =  useGLTF(`${selectPath()}/rooms/Class.glb`) as any

  return (
    <group {...props} dispose={null}>
      <group position={[26.05, 1.37, -22.88]} rotation={[-Math.PI / 2, 0, 1.57]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Blackboard_LP_Blackboard_Bake_0.geometry} material={materials.Blackboard_Bake} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Chalks_LP_Blackboard_Bake_0.geometry} material={materials.Blackboard_Bake} position={[181.3, 0.16, -5.61]} rotation={[-Math.PI / 2, 0, 0.08]} scale={100} />
          <mesh geometry={nodes.Duster_LP_Blackboard_Bake_0.geometry} material={materials.Blackboard_Bake} position={[147.09, 1.44, -5.32]} rotation={[-Math.PI / 2, 0, 3.14]} scale={100} />
        </group>
      </group>
      <group position={[17.05, 0.54, -22.48]} rotation={[-Math.PI / 2, 0, 1.57]} scale={0.01 *REDUCE_SCALE_DOOR}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001__0.geometry} material={materials['Cube.000__0.001']} position={[0, 0.05, 0]} scale={[1, 0.86, 1]} />
          </group>
        </group>
      </group>
      <group position={[20.5, 0.54, -19.04]} rotation={[-Math.PI / 2, 0, 3.14]} scale={0.01*REDUCE_SCALE_DOOR}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001__0001.geometry} material={materials['Cube.000__0.001']} position={[0, 0.06, 0]} scale={[1, 0.7, 1]} />
          </group>
        </group>
      </group>
      <group position={[19.55, 2.8, -18.78]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.002']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[21.53, 2.81, -18.78]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.002']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[16.76, 2.8, -23.47]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['Material.002']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[16.76, 2.81, -21.49]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['Material.002']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[21.6, 0.57, -22.57]} rotation={[0, Math.PI / 2, 0]} scale={[3.5, 1, 4.5]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['Floor.001']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.OutsideWall} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials.InsideWall} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials.MiddleWall} />
      </group>
      <mesh geometry={nodes.Chair015_Material001_0001.geometry} material={materials['Material.004']} position={[20.46, 1.85, -22.52]} rotation={[Math.PI / 2, 0, -1.58]} />
      <mesh geometry={nodes.Chair015_Color_C14_0001.geometry} material={materials['Color_C14.001']} position={[20.41, 1.83, -22.36]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube002__0001.geometry} material={materials['Cube.000__0.001']} />
    </group>
  )
}

useGLTF.preload(`${selectPath()}/rooms/Class.glb`)
