/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\Laboratory.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import {  selectPath } from '../../../Common/Utils/Utils'
import { SCENE_LIGHT_INTENSITY, REDUCE_SCALE_DOOR} from '../Modifiers'
export function Laboratory(props: any) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`${selectPath()}/rooms/Laboratory.glb`) as any;
  const { actions } = useAnimations(animations, group)

  return (
    <group {...props} dispose={null}>
      <group position={[26.34, 0.46, -10.08]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.1}>
        <group position={[19.95, 1.32, 18.71]} scale={0.64}>
          <group position={[0.15, 8.07, 0.01]} rotation={[0, -0.4, 0]} scale={[4.36, 4.36, 4.13]}>
            <mesh geometry={nodes.Object_100.geometry} material={materials['fabric-red']} />
            <mesh geometry={nodes.Object_102.geometry} material={materials['fabric-red']} position={[1.11, 1.26, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.56, 1, 0.8]} />
            <mesh geometry={nodes.Object_104.geometry} material={materials.metallic} position={[1.11, 1.26, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.18, 0.18, 0.19]} />
          </group>
          <mesh geometry={nodes.Object_96.geometry} material={materials.metallic} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.black} position={[-1.67, 0.74, 4.02]} rotation={[0, -0.41, -Math.PI / 2]} scale={[0.51, 0.18, 0.45]} />
        </group>
        <group position={[9.26, 6.9, 48.97]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={4.68}>
          <mesh geometry={nodes.Object_72.geometry} material={materials.metallic} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.metallic} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.metallic} />
        </group>
        <mesh geometry={nodes.Object_82.geometry} material={materials.metallic_dark} position={[12.7, 1.51, 42.1]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={0.24} />
        <mesh geometry={nodes.Object_162.geometry} material={materials.metallic_2} position={[11.69, 1.74, 20.36]} scale={0.33} />
        <mesh geometry={nodes.Object_164.geometry} material={materials['white.004']} position={[8.95, 4.19, 7.45]} scale={[4.4, 2.77, 2.77]} />
        <mesh geometry={nodes.Object_166.geometry} material={materials.metallic} position={[8.95, 4.19, 7.45]} scale={[4.4, 2.77, 2.77]} />
        <mesh geometry={nodes.Object_168.geometry} material={materials.light_blue} position={[8.95, 4.19, 7.45]} scale={[4.4, 2.77, 2.77]} />
        <mesh geometry={nodes.Object_90.geometry} material={materials['light_yellow.001']} position={[9.26, 6.9, 48.97]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={4.68} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.glass} position={[9.26, 6.9, 48.97]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={4.68} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.metallic} position={[9.34, 1.34, 48.88]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={5.62} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.metallic_2} position={[9.27, 1.87, 43.26]} rotation={[Math.PI / 2, 0, 3.13]} scale={[0.96, 0.96, 0.52]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Material} position={[6.82, 17.57, 10.06]} scale={[2.16, 2.77, 5.32]} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.white} position={[8.28, 9.32, 10.71]} rotation={[0, -0.45, 0]} scale={[1.59, 1.98, 1.98]} />
        <mesh geometry={nodes.Object_110.geometry} material={materials['white.006']} position={[9.46, 9.3, 6]} scale={[2.77, 2.77, 1.29]} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.metallic_2} position={[7.43, 1.4, 32.58]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={2.83} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.metallic} position={[7.02, 17.93, 11.79]} scale={[1.46, 2.77, 2.54]} />
        <mesh geometry={nodes.Object_108.geometry} material={materials['white.005']} position={[8.04, 9.3, 18.98]} rotation={[0, 0.69, 0]} scale={[1.76, 0.97, 2.51]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.metallic_2} position={[6.88, 17.93, 5.54]} scale={[1.82, 2.77, 0.46]} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.metallic_2} position={[6.88, 17.93, 6.64]} scale={[1.82, 2.77, 0.46]} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.metallic_2} position={[14.17, 1.41, 43.54]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={1.97} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.floor} position={[4.41, 2.43, 22.95]} rotation={[0, 0, -Math.PI / 2]} scale={0.83} />
        <mesh geometry={nodes.Object_112.geometry} material={materials.white} position={[11.22, 9.3, 14.53]} rotation={[0, 1.12, 0]} scale={1.75} />
        <mesh geometry={nodes.Object_114.geometry} material={materials.black} position={[8.04, 9.3, 18.98]} rotation={[0, 0.69, 0]} scale={[1.76, 0.97, 2.51]} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.gray} position={[8.04, 9.3, 18.98]} rotation={[0, 0.69, 0]} scale={[1.76, 0.97, 2.51]} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.gray} position={[11.22, 9.3, 14.53]} rotation={[0, 1.12, 0]} scale={1.75} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.light_green} position={[11.22, 9.3, 14.53]} rotation={[0, 1.12, 0]} scale={1.75} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.black} position={[8.28, 9.32, 10.71]} rotation={[0, -0.45, 0]} scale={[1.59, 1.98, 1.98]} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.gray} position={[8.04, 9.3, 18.98]} rotation={[0, 0.69, 0]} scale={[1.76, 0.97, 2.51]} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.light_blue} position={[9.46, 9.3, 6]} scale={[2.77, 2.77, 1.29]} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.gray} position={[8.04, 9.3, 18.98]} rotation={[0, 0.69, 0]} scale={[1.76, 0.97, 2.51]} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.light_yellow} position={[7.43, 1.4, 32.58]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={2.83} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.light_blue} position={[7.02, 17.93, 11.79]} scale={[1.46, 2.77, 2.54]} />
        <mesh geometry={nodes.Object_160.geometry} material={materials['gray.002']} position={[8.94, 7.89, 13.44]} scale={[4.44, 4.44, 8.79]} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.black} position={[9.74, 1.67, 42.51]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={2.77} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.black} position={[9, 1.67, 43.14]} rotation={[-Math.PI, -0.01, -Math.PI]} scale={2.77} />
        <mesh geometry={nodes.Object_130.geometry} material={materials.black} position={[6.68, 9.62, 4.98]} scale={2.77} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.black} position={[10.31, 9.45, 14.08]} scale={2.77} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.black} position={[6.39, 12.06, 8.95]} scale={2.77} />
      </group>
      <group position={[21.53, 0.51, -16.01]} rotation={[-Math.PI / 2, 0, 3.14]} scale={0.01 * REDUCE_SCALE_DOOR}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001__0.geometry} material={materials['Cube.000__0']} position={[0, 0.07, -0.03]} scale={[1, 0.64, 1]} />
          </group>
        </group>
      </group>
      <group position={[22.58, 2.77, -16.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.012']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[20.6, 2.78, -16.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.011']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[17.87, 2.77, -14.51]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['Material.014']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[17.87, 2.78, -12.53]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.28}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['Material.013']} position={[-0.07, 0, 0]} />
        </group>
        <group position={[-0.06, 0.26, 0.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
          <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[18.15, 0.51, -13.52]} rotation={[-Math.PI / 2, 0, 1.57]} scale={0.01 * REDUCE_SCALE_DOOR}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001__0001.geometry} material={materials['Cube.000__0.001']} position={[0, 0.07, -0.03]} scale={[1, 0.83, 1]} />
          </group>
        </group>
      </group>
      <group position={[22.18, 0.53, -12.92]} rotation={[0, -Math.PI / 2, 0]} scale={[3, 1, 4]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['Floor.001']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.OutsideWall} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials.InsideWall} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials.MiddleWall} />
      </group>
      <mesh geometry={nodes.Cube002__0.geometry} material={materials['Cube.000__0']} />
    </group>
  )
}

useGLTF.preload(`${selectPath()}/rooms/Laboratory.glb`)
