/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Room_library.gltf
*/

import React, { useRef, useState } from 'react'
import { useAnimations, useGLTF, Html } from '@react-three/drei'
import {  selectPath } from '../../../Common/Utils/Utils'
import '../../Styles/GameScene.scss'
import { SCENE_LIGHT_INTENSITY, REDUCE_SCALE_DOOR} from '../Modifiers'
export function Library(props: any) {
  const group = useRef()
  const [show, setShow] = useState(false);
  const { nodes, materials, animations } = useGLTF(`${selectPath()}/rooms/Library.glb`) as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.legs_geo4_wood_mat_0.geometry} material={materials.wood_mat} />
      <mesh geometry={nodes.sofa_geo_Leather_mat_0.geometry} material={materials.Leather_mat} />
      <mesh geometry={nodes.sofa_geo_Leather_mat_0001.geometry} material={materials.Leather_mat} />
      <mesh geometry={nodes.Object_10001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_11001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_12001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_13001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_14001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_15001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_16001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_17001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_18001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_19001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_2001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_20001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_21001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_22001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_23001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_24001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_25001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_26001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_27001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_3001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_4001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_5001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_6001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_7001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_8001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_9001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.legs_geo4_wood_mat_0001.geometry} material={materials.wood_mat} />
      <mesh geometry={nodes.sofa_geo_Leather_mat_0002.geometry} material={materials.Leather_mat} />
      <mesh geometry={nodes.sofa_geo_Leather_mat_0003.geometry} material={materials.Leather_mat} />
      <mesh geometry={nodes.Bookcase_1_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.Books_low_Books002_0001.geometry} material={materials['Books.001']} />
      <mesh geometry={nodes.Draw_1_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.Draw_2_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.Draw_3_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.ARMCHAIR_TEXSET_A_0.geometry} material={materials.TEXSET_A} />
      <mesh geometry={nodes.COFFEETABLE_TEXSET_A_0.geometry} material={materials.TEXSET_A} />
      <mesh geometry={nodes.FLOORLAMP_TEXSET_A_0.geometry} material={materials.TEXSET_A} />
      <mesh geometry={nodes.Bookcase_1_low_Bookcase001_0003.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.Books_low_Books002_0003.geometry} material={materials['Books.001']} />
      <mesh geometry={nodes.Draw_1_low_Bookcase001_0003.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.Draw_2_low_Bookcase001_0003.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.Draw_3_low_Bookcase001_0003.geometry} material={materials['Bookcase.002']} />
      <mesh geometry={nodes.pCylinder6_blinn1_0.geometry} material={materials['blinn1.001']} />
      <mesh geometry={nodes.victorian_chair_cloth_cloth_0.geometry} material={materials.cloth} />
      <mesh geometry={nodes.victorian_chair_wood_wood_0.geometry} material={materials.wood} />
      <mesh geometry={nodes.Object_2004.geometry} material={materials['material_0.002']} />
      <mesh geometry={nodes.Cube001__0.geometry} material={materials['Cube.000__0']} />
      <mesh geometry={nodes.Cube001__0001.geometry} material={materials['Cube.000__0']} />
      <mesh geometry={nodes.Bookcase_1_low_Bookcase001_0002.geometry} material={materials['Bookcase.001']} />
      <mesh geometry={nodes.Books_low_Books002_0002.geometry} material={materials['Books.002']} />
      <mesh geometry={nodes.Draw_1_low_Bookcase001_0002.geometry} material={materials['Bookcase.001']} />
      <mesh geometry={nodes.Draw_2_low_Bookcase001_0002.geometry} material={materials['Bookcase.001']} />
      <mesh geometry={nodes.Draw_3_low_Bookcase001_0002.geometry} material={materials['Bookcase.001']} />
      <group position={[3.62, 2.99, -19.72]} rotation={[Math.PI, 0, Math.PI]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.003']} />
      <group position={[5.6, 3.02, -19.73]} rotation={[Math.PI, 0, Math.PI]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.003']} />
      <group position={[8.38, 2.99, -20.49]} rotation={[0, -1.57, 0]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['Material.003']} />
      <group position={[8.37, 3.02, -22.47]} rotation={[0, -1.57, 0]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials.OutsideWall} />
      <mesh geometry={nodes.Plane001_2.geometry} material={materials.MiddleWall} />
      <mesh geometry={nodes.Plane001_3.geometry} material={materials.CarpetInsideWall} />
    </group>
  )
}

useGLTF.preload(`${selectPath()}/rooms/Library.glb`)
