/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Room_library.gltf
*/


import React, { useRef, useState } from 'react'
import { useAnimations, useGLTF, Html } from '@react-three/drei'
import {  selectPath } from '../../../Common/Utils/Utils'
import '../../Styles/GameScene.scss'
import { SCENE_LIGHT_INTENSITY, REDUCE_SCALE_DOOR} from '../Modifiers'
export function Observatory(props: any) {
  const group = useRef()
  const [show, setShow] = useState(false);
  const { nodes, materials } = useGLTF(`${selectPath()}/rooms/Observatory.glb`) as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2005.geometry} material={materials['simple_desk_Mat.001']} />
      <mesh geometry={nodes.Object_4002.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Object_6001.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.sidushka001_tkan_0.geometry} material={materials['tkan.001']} />
      <mesh geometry={nodes.BezierCurve003_metall_0.geometry} material={materials['metall.001']} />
      <mesh geometry={nodes.BezierCurve004_metall_0.geometry} material={materials['metall.001']} />
      <mesh geometry={nodes.BezierCurve005_plastic3_2_0.geometry} material={materials['plastic3_2.001']} />
      <mesh geometry={nodes.Cylinder_metall_0.geometry} material={materials['metall.001']} />
      <mesh geometry={nodes.Cylinder001_metall_0.geometry} material={materials['metall.001']} />
      <mesh geometry={nodes.Cylinder002_plastic3_2_0.geometry} material={materials['plastic3_2.001']} />
      <mesh geometry={nodes.Cylinder003_plastic3_2_0.geometry} material={materials['plastic3_2.001']} />
      <mesh geometry={nodes.sidushka_plastic3_2_0.geometry} material={materials['plastic3_2.001']} />
      <mesh geometry={nodes.spinka_plastic3_2_0.geometry} material={materials['plastic3_2.001']} />
      <mesh geometry={nodes.spinka001_tkan_0.geometry} material={materials['tkan.001']} />
      <mesh geometry={nodes.arrow_degrees_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.attachment_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.bigScope_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.bolts_degree_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.bolts_leg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.bolts_leg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.bolts_leg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.cap_attach_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.cap_chain_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.cap_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.center_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.chain_leg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.chain_leg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.chain_leg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.compas_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.connection1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.connection2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.degrees_cil_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.degrees_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.glass_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.grip_leg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.grip_leg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.grip_leg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_cap_attach_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_cap_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_center1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_center2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_center3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_leg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_leg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.helix_leg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.inside_leg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.inside_leg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.inside_leg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.lilScope_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.outside_leg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.outside_leg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.outside_leg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.plateau_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.rondeel_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.spanleg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.spanleg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.spanleg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.turnable1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.turnable2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.turnthing_leg1_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.turnthing_leg2_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.turnthing_leg3_lowpoly__0.geometry} material={materials['Scene_-_Root']} />
      <mesh geometry={nodes.frame_Material004_0.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane001_Material003_0.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.frame_Material004_0001.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Plane_Material001_0001.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Plane001_Material003_0001.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube001__0.geometry} material={materials['Cube.000__0']} />
      <group position={[19.37, 2.92, -6.25]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.012']} />
      <group position={[17.39, 2.95, -6.25]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.012']} />
      <group position={[14.6, 2.92, -4.46]} rotation={[0, 1.57, 0]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['Material.012']} />
      <group position={[14.6, 2.95, -2.48]} rotation={[0, 1.57, 0]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['Material.012']} />
      <group position={[23.37, 3.04, -2.5]} rotation={[0, -1.57, 0]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial004.geometry} material={materials['Material.012']} />
      <group position={[23.37, 3.07, -4.48]} rotation={[0, -1.57, 0]} scale={0.16}>
        <pointLight intensity={SCENE_LIGHT_INTENSITY} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.defaultMaterial005.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Cube001__0001.geometry} material={materials['Cube.000__0']} />
      <mesh geometry={nodes.Cube001__0002.geometry} material={materials['Cube.000__0']} />
      <mesh geometry={nodes.Plane001_1.geometry} material={materials['Floor.001']} />
      <mesh geometry={nodes.Plane001_2.geometry} material={materials.OutsideWall} />
      <mesh geometry={nodes.Plane001_3.geometry} material={materials.InsideWall} />
      <mesh geometry={nodes.Plane001_4.geometry} material={materials.MiddleWall} />
    </group>
  )
}


useGLTF.preload(`${selectPath()}/rooms/Observatory.glb`)
