/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Room_class.gltf
*/

import React, { useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { REDUCE_SCALE_DOOR, selectPath } from '../Utils/Utils'

export function Class(props: any) {
  const group = useRef()
  const { nodes, materials, animations } =  useGLTF(`${selectPath()}/rooms/Class.glb`) as any
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Class">
        <group name="Class_1" position={[2.71, 0.54, -4.56]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={0.1}>
          <group name="prop_books_03_inst_001001" position={[-4.1, -2.18, -6.29]} scale={0} />
          <group name="prop_books_05_inst_001001" position={[-4.02, -2.79, -6.08]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
          <group name="Sketchfab_model004" position={[-44.76, 3.81, -38.5]} rotation={[-Math.PI / 2, 0, 0]} scale={4.14}>
            <group name="165f13c07a5b4ff2a1373296c6134d2efbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <group name="RootNode002">
                <group name="blackboard" position={[0, -1.63, 0]} scale={[1.31, 1.31, 1]}>
                  <group name="blackboard_lambert1_0" position={[1922.07, 7.62, 37.6]}>
                    <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Material_42} />
                    <mesh name="Mesh_1_1" geometry={nodes.Mesh_1_1.geometry} material={materials.Material_43} />
                    <mesh name="Mesh_1_2" geometry={nodes.Mesh_1_2.geometry} material={materials.Material_44} />
                    <mesh name="Mesh_1_3" geometry={nodes.Mesh_1_3.geometry} material={materials.Material_45} />
                    <mesh name="Mesh_1_4" geometry={nodes.Mesh_1_4.geometry} material={materials.Material_46} />
                    <mesh name="Mesh_1_5" geometry={nodes.Mesh_1_5.geometry} material={materials.Material_53} />
                    <mesh name="Mesh_1_6" geometry={nodes.Mesh_1_6.geometry} material={materials.Material_54} />
                    <mesh name="Mesh_1_7" geometry={nodes.Mesh_1_7.geometry} material={materials.Material_55} />
                    <mesh name="Mesh_1_8" geometry={nodes.Mesh_1_8.geometry} material={materials.Material_56} />
                    <mesh name="Mesh_1_9" geometry={nodes.Mesh_1_9.geometry} material={materials.Material_57} />
                    <mesh name="Mesh_1_10" geometry={nodes.Mesh_1_10.geometry} material={materials.Material_58} />
                    <mesh name="Mesh_1_11" geometry={nodes.Mesh_1_11.geometry} material={materials.Material_59} />
                    <mesh name="Mesh_1_12" geometry={nodes.Mesh_1_12.geometry} material={materials.Material_62} />
                    <mesh name="Mesh_1_13" geometry={nodes.Mesh_1_13.geometry} material={materials.Material_63} />
                    <mesh name="Mesh_1_14" geometry={nodes.Mesh_1_14.geometry} material={materials.Material_66} />
                    <mesh name="Mesh_1_15" geometry={nodes.Mesh_1_15.geometry} material={materials['Material_6.001']} />
                    <mesh name="Mesh_1_16" geometry={nodes.Mesh_1_16.geometry} material={materials.Material_67} />
                    <mesh name="Mesh_1_17" geometry={nodes.Mesh_1_17.geometry} material={materials.Material_68} />
                    <mesh name="Mesh_1_18" geometry={nodes.Mesh_1_18.geometry} material={materials.Material_69} />
                    <mesh name="Mesh_1_19" geometry={nodes.Mesh_1_19.geometry} material={materials.Material_71} />
                    <mesh name="Mesh_1_20" geometry={nodes.Mesh_1_20.geometry} material={materials.Material_72} />
                    <mesh name="Mesh_1_21" geometry={nodes.Mesh_1_21.geometry} material={materials.Material_76} />
                    <mesh name="Mesh_1_22" geometry={nodes.Mesh_1_22.geometry} material={materials.Material_77} />
                    <mesh name="Mesh_1_23" geometry={nodes.Mesh_1_23.geometry} material={materials.Material_78} />
                    <mesh name="Mesh_1_24" geometry={nodes.Mesh_1_24.geometry} material={materials['Material_19.001']} />
                    <mesh name="Mesh_1_25" geometry={nodes.Mesh_1_25.geometry} material={materials.Board_einstein} />
                  </group>
                </group>
                <group name="chalk_1" position={[-16.24, 0.81, 769.23]} />
                <group name="chalk_2" position={[0, 0.81, 0]} />
                <group name="chalk_3" position={[0, 0.81, 0]} />
                <group name="eraser" position={[0, 0.81, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="2c09cf8729ca4c67a408f7a9d8914fa2fbx" position={[0.06, 0.54, -7.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <group name="Object_2">
            <group name="RootNode">
              <group name="LP_Desk_Chair" rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Area002" position={[2.32, 1.42, -7.51]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
        <group name="DoorGroup" position={[8.91, 0.51, -3.49]} rotation={[-Math.PI / 2, 0, -1.57]} scale={0.01 * REDUCE_SCALE_DOOR}>
          <group name="0d6cf17bcfde48d9b7d35e076d70e1e3fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2001">
              <group name="RootNode001">
                <group name="Cube000" position={[-83.59, 29.67, -17.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Cube002" position={[1.57, -0.18, 1.61]}>
                    <mesh name="Cube002__0" geometry={nodes.Cube002__0.geometry} material={materials['Cube.000__0.001']} />
                  </group>
                  <mesh name="Cube000__0" geometry={nodes.Cube000__0.geometry} material={materials['Cube.000__0.001']} />
                </group>
                <group name="Cube001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube001__0" geometry={nodes.Cube001__0.geometry} material={materials['Cube.000__0.001']} position={[0, 0.05, 0]} scale={[1, 0.86, 1]} />
                </group>
                <group name="Cube003" position={[0, 100, 9.27]} rotation={[-Math.PI / 2, 0, 0]} scale={[10, 100, 100]} />
                <group name="Cube004" position={[0, 100, -9.44]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[10, 100, 100]} />
              </group>
            </group>
          </group>
        </group>
        <group name="DoorGroup001" position={[5.46, 0.51, -6.94]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01 * REDUCE_SCALE_DOOR}>
          <group name="0d6cf17bcfde48d9b7d35e076d70e1e3fbx001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2002">
              <group name="RootNode003">
                <group name="Cube009" position={[-83.59, 29.67, -17.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Cube008" position={[1.57, -0.18, 1.61]}>
                    <mesh name="Cube002__0001" geometry={nodes.Cube002__0001.geometry} material={materials['Cube.000__0.002']} />
                  </group>
                  <mesh name="Cube000__0001" geometry={nodes.Cube000__0001.geometry} material={materials['Cube.000__0.002']} />
                </group>
                <group name="Cube005" position={[0, 100, -9.44]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[10, 100, 100]} />
                <group name="Cube006" position={[0, 100, 9.27]} rotation={[-Math.PI / 2, 0, 0]} scale={[10, 100, 100]} />
                <group name="Cube007" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube001__0001" geometry={nodes.Cube001__0001.geometry} material={materials['Cube.000__0.002']} position={[0, 0.06, 0]} scale={[1, 0.7, 1]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="LampLeft" position={[6.41, 2.77, -7.2]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
          <group name="Collada_visual_scene_group001" position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="Cylinder001">
              <mesh name="defaultMaterial001" geometry={nodes.defaultMaterial001.geometry} material={materials['Material.002']} position={[-0.07, 0, 0]} />
            </group>
          </group>
          <group name="LightLeft" position={[-0.06, 0.26, 0.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
            <pointLight name="LightLeft_Orientation" intensity={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
        </group>
        <group name="LampRight" position={[4.43, 2.78, -7.19]} rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
          <group name="Collada_visual_scene_group" position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="Cylinder028">
              <mesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials['Material.001']} position={[-0.07, 0, 0]} />
            </group>
          </group>
          <group name="LightRight" position={[-0.06, 0.26, 0.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
            <pointLight name="LightRight_Orientation" intensity={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
        </group>
        <group name="LampLeft001" position={[9.2, 2.77, -2.5]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.28}>
          <group name="Collada_visual_scene_group003" position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="Cylinder003">
              <mesh name="defaultMaterial003" geometry={nodes.defaultMaterial003.geometry} material={materials['Material.007']} position={[-0.07, 0, 0]} />
            </group>
          </group>
          <group name="LightLeft001" position={[-0.06, 0.26, 0.46]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
            <pointLight name="LightLeft001_Orientation" intensity={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
        </group>
        <group name="LampRight001" position={[9.2, 2.78, -4.48]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.28}>
          <group name="Collada_visual_scene_group002" position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
            <group name="Cylinder002">
              <mesh name="defaultMaterial002" geometry={nodes.defaultMaterial002.geometry} material={materials['Material.006']} position={[-0.07, 0, 0]} />
            </group>
          </group>
          <group name="LightRight001" position={[-0.06, 0.26, 0.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.55}>
            <pointLight name="LightRight001_Orientation" intensity={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
        </group>
        <group name="Room" position={[4.36, 0.53, -3.41]} rotation={[0, -Math.PI / 2, 0]} scale={[3.5, 1, 4.5]}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Floor.001']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.OutsideWall} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.InsideWall} />
          <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.MiddleWall} />
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload('/models/rooms/Room_class.gltf')
