/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Room_library.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RoomLibrary(props: any) {
  const { nodes, materials } = useGLTF('./TheEinsteinsCrime/models/rooms/Room_library.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[5.62, 2.54, -19.98]} scale={0.24}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.35, 2.54, -19.98]} scale={0.24}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[8.2, 2.53, -22.57]} scale={0.24}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[8.21, 2.54, -20.44]} scale={0.24}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[1.82, 0.6, -24.6]} rotation={[-Math.PI / 2, 0, 0]} scale={1.08}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <group scale={0.39}>
            <mesh geometry={nodes.sofa_geo_Leather_mat_0.geometry} material={materials.Leather_mat} />
            <mesh geometry={nodes.sofa_geo_Leather_mat_0001.geometry} material={materials.Leather_mat} />
          </group>
          <mesh geometry={nodes.legs_geo4_wood_mat_0.geometry} material={materials.wood_mat} scale={0.39} />
        </group>
      </group>
      <group position={[1.2, 1.37, -22.41]} rotation={[-1.75, 0.46, -1.08]} scale={0}>
        <mesh geometry={nodes.Object_10001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_11001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_12001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_13001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_14001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_15001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_16001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_17001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_18001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_19001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_2001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_20001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_21001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_22001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_23001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_24001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_25001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_26001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_27001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_3001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_5001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_6001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_7001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_8001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
        <mesh geometry={nodes.Object_9001.geometry} material={materials['material_0.001']} position={[-75.77, 23.48, 8.32]} />
      </group>
      <group position={[1.87, 1.78, -25.5]} rotation={[-Math.PI / 2, 0, -1.57]} scale={1.14}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bookcase_1_low_Bookcase001_0.geometry} material={materials['Bookcase.001']} />
            <mesh geometry={nodes.Books_low_Books002_0.geometry} material={materials['Books.002']} />
            <mesh geometry={nodes.Draw_1_low_Bookcase001_0.geometry} material={materials['Bookcase.001']} position={[0.03, 0, 0]} />
            <mesh geometry={nodes.Draw_2_low_Bookcase001_0.geometry} material={materials['Bookcase.001']} position={[0.02, 0, 0]} />
            <mesh geometry={nodes.Draw_3_low_Bookcase001_0.geometry} material={materials['Bookcase.001']} position={[0.01, 0, 0]} />
          </group>
        </group>
      </group>
      <group position={[3.24, 0.6, -22.93]} rotation={[-Math.PI / 2, 0, -1.57]} scale={1.08}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <group scale={0.39}>
            <mesh geometry={nodes.sofa_geo_Leather_mat_0002.geometry} material={materials['Leather_mat.001']} />
            <mesh geometry={nodes.sofa_geo_Leather_mat_0003.geometry} material={materials['Leather_mat.001']} />
          </group>
          <mesh geometry={nodes.legs_geo4_wood_mat_0001.geometry} material={materials['wood_mat.001']} scale={0.39} />
        </group>
      </group>
      <group position={[3.89, 1.79, -25.49]} rotation={[-Math.PI / 2, 0, -1.57]} scale={1.13}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bookcase_1_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} />
            <mesh geometry={nodes.Books_low_Books002_0001.geometry} material={materials['Books.001']} />
            <mesh geometry={nodes.Draw_1_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} position={[0.03, 0, 0]} />
            <mesh geometry={nodes.Draw_2_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} position={[0.02, 0, 0]} />
            <mesh geometry={nodes.Draw_3_low_Bookcase001_0001.geometry} material={materials['Bookcase.002']} position={[0.01, 0, 0]} />
          </group>
        </group>
      </group>
      <group position={[4.74, 0.32, -23.47]} rotation={[-Math.PI / 2, 0, 0]} scale={1.2}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[0, 0, 0.19]}>
              <mesh geometry={nodes.ARMCHAIR_TEXSET_A_0.geometry} material={materials.TEXSET_A} position={[-268.23, -131.02, 24.18]} rotation={[0, 0, 2.94]} />
            </group>
            <group position={[23.31, -100.42, 0]} rotation={[0, 0, 0.07]}>
              <mesh geometry={nodes.COFFEETABLE_TEXSET_A_0.geometry} material={materials.TEXSET_A} position={[-261.42, 73.8, 24.27]} rotation={[0, 0, -1.68]} />
            </group>
            <group position={[80.27, 19.27, 138.46]} rotation={[-0.02, 0.05, 0.69]} scale={1.03}>
              <group position={[0, 0, -10.32]}>
                <mesh geometry={nodes.FLOORLAMP_TEXSET_A_0.geometry} material={materials.TEXSET_A} position={[-110.57, 178.18, 14.89]} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[5.93, 1.79, -25.49]} rotation={[-Math.PI / 2, 0, -1.57]} scale={[1.08, 1.17, 1.13]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bookcase_1_low_Bookcase001_0003.geometry} material={materials['Bookcase.004']} />
            <mesh geometry={nodes.Books_low_Books002_0003.geometry} material={materials['Books.004']} />
            <mesh geometry={nodes.Draw_1_low_Bookcase001_0003.geometry} material={materials['Bookcase.004']} position={[0.03, 0, 0]} />
            <mesh geometry={nodes.Draw_2_low_Bookcase001_0003.geometry} material={materials['Bookcase.004']} position={[0.02, 0, 0]} />
            <mesh geometry={nodes.Draw_3_low_Bookcase001_0003.geometry} material={materials['Bookcase.004']} position={[0.01, 0, 0]} />
          </group>
        </group>
      </group>
      <group position={[7.47, 1.79, -24.01]} rotation={[-Math.PI / 2, 0, -3.14]} scale={[1.2, 1.2, 1.13]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bookcase_1_low_Bookcase001_0002.geometry} material={materials['Bookcase.005']} />
            <mesh geometry={nodes.Books_low_Books002_0002.geometry} material={materials['Books.005']} />
            <mesh geometry={nodes.Draw_1_low_Bookcase001_0002.geometry} material={materials['Bookcase.005']} position={[0.03, 0, 0]} />
            <mesh geometry={nodes.Draw_2_low_Bookcase001_0002.geometry} material={materials['Bookcase.005']} position={[0.02, 0, 0]} />
            <mesh geometry={nodes.Draw_3_low_Bookcase001_0002.geometry} material={materials['Bookcase.005']} position={[0.01, 0, 0]} />
          </group>
        </group>
      </group>
      <group position={[5.31, 0.49, -23.26]} rotation={[-Math.PI / 2, 0, 0]} scale={0.33}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.pCylinder6_blinn1_0.geometry} material={materials['blinn1.001']} position={[0.18, 0.47, -0.5]} rotation={[0, 0.75, 0]} />
        </group>
      </group>
      <group position={[4.43, 0.61, -23.56]} rotation={[-Math.PI / 2, 0, 1.33]} scale={0.98}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.victorian_chair_cloth_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.victorian_chair_wood_wood_0.geometry} material={materials.wood} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[6.48, 0.61, -24.04]} rotation={[-Math.PI / 2, 0, -0.45]} scale={0.99}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.victorian_chair_cloth_cloth_0001.geometry} material={materials['cloth.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.victorian_chair_wood_wood_0001.geometry} material={materials['wood.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[0.89, 0, -23.33]} rotation={[-Math.PI / 2, 0, 1.57]} scale={0.36}>
        <group position={[-3.56, 2.19, 1.37]}>
          <mesh geometry={nodes.Object_2002.geometry} material={materials['None.001']} position={[-1.19, -21.91, 0.03]} scale={[1.08, 1.35, 1]} />
          <mesh geometry={nodes.Object_3.geometry} material={materials['Material.006']} position={[-1.19, -21.98, 0.02]} scale={[1.08, 0.88, 1]} />
        </group>
      </group>
      <group position={[4.48, 0.49, -19.69]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.26, 0.32, 0.24]}>
        <mesh geometry={nodes.Object_2003.geometry} material={materials['None.002']} position={[0, 1.42, 0]} scale={[1.54, 1.92, 1.5]} />
        <mesh geometry={nodes.Object_3002.geometry} material={materials['Material.007']} position={[-0.05, 1.3, 0]} scale={[1.5, 0.72, 1.5]} />
      </group>
      <group position={[7.45, 2.39, -23.31]} rotation={[-Math.PI / 2, 0, -1.57]} scale={0.24}>
        <group position={[3.1, 3.02, 0.07]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.008']} position={[-0.07, 0, 0]} />
        </group>
      </group>
      <group position={[8.17, 2.39, -21.05]} rotation={[-Math.PI / 2, 0, -1.57]} scale={0.24}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.009']} position={[2.52, 0.03, 0]} />
        </group>
      </group>
      <group position={[5.62, 2.39, -20.04]} rotation={[-Math.PI / 2, 0, -3.14]} scale={0.24}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['Material.010']} position={[0, 0, -0.38]} />
        </group>
      </group>
      <group position={[3.35, 2.39, -20.04]} rotation={[-Math.PI / 2, 0, -3.14]} scale={0.24}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['Material.011']} position={[0, 0, -0.4]} />
        </group>
      </group>
      <group position={[3.66, 0.49, -22.85]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Object_2004.geometry} material={materials['material_0.002']} position={[-1375.26, -745.17, 355.98]} />
      </group>
      <group position={[4.03, 0.5, -23.06]} scale={[4, 1, 3.05]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['Room_wall_interior.001']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Room_floor.001']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Room_wall_exterior.001']} />
      </group>
    </group>
  )
}

// useGLTF.preload('/models/rooms/Room_library.gltf')
