/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Room_class.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RoomClass(props: any) {
  const { nodes, materials } = useGLTF('./models/rooms/Room_class.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[-8.72, 3.33, 8.99]} scale={0.57}>
        <directionalLight intensity={1} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[2.71, 0.54, -4.56]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={0.1}>
        <group position={[-44.76, 3.81, -38.5]} rotation={[-Math.PI / 2, 0, 0]} scale={4.14}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group position={[0, -1.63, 0]} scale={[1.31, 1.31, 1]}>
              <group position={[1922.07, 7.62, 37.6]}>
                <mesh geometry={nodes.Mesh_1.geometry} material={materials.Material_42} />
                <mesh geometry={nodes.Mesh_1_1.geometry} material={materials.Material_43} />
                <mesh geometry={nodes.Mesh_1_2.geometry} material={materials.Material_44} />
                <mesh geometry={nodes.Mesh_1_3.geometry} material={materials.Material_45} />
                <mesh geometry={nodes.Mesh_1_4.geometry} material={materials.Material_46} />
                <mesh geometry={nodes.Mesh_1_5.geometry} material={materials.Material_53} />
                <mesh geometry={nodes.Mesh_1_6.geometry} material={materials.Material_54} />
                <mesh geometry={nodes.Mesh_1_7.geometry} material={materials.Material_55} />
                <mesh geometry={nodes.Mesh_1_8.geometry} material={materials.Material_56} />
                <mesh geometry={nodes.Mesh_1_9.geometry} material={materials.Material_57} />
                <mesh geometry={nodes.Mesh_1_10.geometry} material={materials.Material_58} />
                <mesh geometry={nodes.Mesh_1_11.geometry} material={materials.Material_59} />
                <mesh geometry={nodes.Mesh_1_12.geometry} material={materials.Material_62} />
                <mesh geometry={nodes.Mesh_1_13.geometry} material={materials.Material_63} />
                <mesh geometry={nodes.Mesh_1_14.geometry} material={materials.Material_66} />
                <mesh geometry={nodes.Mesh_1_15.geometry} material={materials['Material_6.001']} />
                <mesh geometry={nodes.Mesh_1_16.geometry} material={materials.Material_67} />
                <mesh geometry={nodes.Mesh_1_17.geometry} material={materials.Material_68} />
                <mesh geometry={nodes.Mesh_1_18.geometry} material={materials.Material_69} />
                <mesh geometry={nodes.Mesh_1_19.geometry} material={materials.Material_71} />
                <mesh geometry={nodes.Mesh_1_20.geometry} material={materials.Material_72} />
                <mesh geometry={nodes.Mesh_1_21.geometry} material={materials.Material_76} />
                <mesh geometry={nodes.Mesh_1_22.geometry} material={materials.Material_77} />
                <mesh geometry={nodes.Mesh_1_23.geometry} material={materials.Material_78} />
                <mesh geometry={nodes.Mesh_1_24.geometry} material={materials['Material_19.001']} />
                <mesh geometry={nodes.Mesh_1_25.geometry} material={materials.Board_einstein} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[8.97, 0.54, -3.55]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.38}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials.None} scale={[1, 1, 0.84]} />
        <group position={[0, 0.06, 0]} scale={[1, 1.55, 0.84]}>
          <mesh geometry={nodes.Object_1.geometry} material={materials.Wall_exterior} />
          <mesh geometry={nodes.Object_1_1.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Object_1_2.geometry} material={materials.Wall_interior} />
        </group>
      </group>
      <group position={[5.51, 0.54, -7.03]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.35, 0.38, 0.38]}>
        <mesh geometry={nodes.Object_2002.geometry} material={materials['None.001']} scale={[1, 1, 0.84]} />
      </group>
      <group position={[4.5, 2.35, -7.26]} scale={0.1}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[6.46, 2.35, -7.26]} scale={0.1}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[9.16, 2.35, -2.57]} scale={0.1}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[9.17, 2.35, -4.53]} scale={0.1}>
        <pointLight intensity={1} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[6.47, 2.26, -7.22]} rotation={[-Math.PI / 2, 0, 0]} scale={0.19}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.003']} position={[-0.07, 0, 0]} />
        </group>
      </group>
      <group position={[9.11, 2.25, -4.52]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.19}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials['Material.004']} position={[-0.07, 0, 0]} />
        </group>
      </group>
      <group position={[9.11, 2.26, -2.56]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.19}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['Material.005']} position={[-0.07, 0, 0]} />
        </group>
      </group>
      <group position={[4.51, 2.25, -7.22]} rotation={[-Math.PI / 2, 0, 0]} scale={0.19}>
        <group position={[0.01, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.008']} position={[-0.07, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

// useGLTF.preload('/models/rooms/Room_class.gltf')
