/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\Tesla.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { selectPath } from '../../Utils/Utils';

export function Tesla(props: any) {
  const { nodes, materials } = useGLTF( `${selectPath()}/characters/Tesla.glb`) as any;
  console.log(props)
  return (
    <group  dispose={null}>
      <mesh geometry={nodes.Object_2001.geometry} material={materials.material_0} position={[0.51, 1.5, -0.47]} rotation={[-1.58 , 0, -0.26 + props.rotationZ]} scale={0.24} />
    </group>
  )
}

// useGLTF.preload('/Tesla.glb')
