/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\Tesla.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { selectPath } from "../../../Common/Utils/Utils";
import { MeshStandardMaterial } from "three";

export interface IPieceProp{
  userIndex: number
}

export function Piece(props: IPieceProp) {
  const { nodes, } = useGLTF(
    `${selectPath()}/characters/Piece.glb`
  ) as any;
  const materialByUser = (userIndex: number) => {
    switch(userIndex){
      case 0: return new MeshStandardMaterial({color: 0xff0000});
      case 1: return new MeshStandardMaterial({color: 0x008000});
      case 2: return new MeshStandardMaterial({color: 0x0000ff});
      case 3: return new MeshStandardMaterial({color: 0xffff00});
      default: return new MeshStandardMaterial({color: 0xffffff});
    }
  }
  return (
    <group  dispose={null}>
      <mesh geometry={nodes.Player.geometry} material={materialByUser(props?.userIndex)} position={[0.51, 1.16, -0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload(`${selectPath()}/characters/Piece.glb`)
