/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\Tesla.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { selectPath } from '../../../../Utils/Utils';

export function Davinci(props: any) {
  const { nodes, materials } = useGLTF(
    `${selectPath()}/characters/Davinci.glb`
  ) as any;
  let rotation = props.rotationZ;
  return (
    // <group {...props} dispose={null} rotation={[-Math.PI, -Math.PI / 2,0 ]}>
    //   <mesh
    //     geometry={nodes.Davinci.geometry}
    //     material={materials.material_0}
    //     position={[0.92, -0.01, -0.37]}
    //     rotation={[0, props.rotationZ, 0]}
    //     scale={0.02}
    //   />
    // </group>
    <group {...props} dispose={null}>
    <mesh geometry={nodes.Davinci.geometry} material={materials.material_0} position={[0.51, 0.86, -0.5]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.02} />
  </group>
  );
}

useGLTF.preload(  `${selectPath()}/characters/Davinci.glb`)
